version: 2.1

parameters:
  # This parameter is used to trigger the main workflow
  trigger_doc_pipeline:
    type: boolean
    default: true
  build_docs:
    type: boolean
    default: true

executors:
  node:
    docker:
      - image: circleci/python:3.8.6

jobs:
  build_and_deploy_docs:
    executor: node
    working_directory: ~/project/
    steps:
      - when:
          condition: << pipeline.parameters.build_docs >>
          steps:
            - checkout:
                path: ~/project
            - run:
                name: build
                command: |
                  pip install --upgrade pip
                  pip install -r requirements.txt
                  python --version ; pip --version ; pwd ; ls
                  python mkdocs build --clean
                  mkdocs build ; mkdocs gh-deploy

workflows:
  version: 2

  build_and_deploy_docs_workflow:
    when: << pipeline.parameters.trigger_doc_pipeline >>
    jobs:
      - build_and_deploy_docs:
          filters:
            branches:
              ignore:
                - gh-pages
